# Generated by Django 4.2.3 on 2023-07-26 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Payment Statuses',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='payments.paymentstatus'),
            preserve_default=False,
        ),
    ]
