# Generated by Django 4.2.3 on 2023-07-26 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentstatus_payment_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='timestamp',
            new_name='date_paid',
        ),
    ]
