# Generated by Django 4.2.3 on 2023-07-26 22:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_rename_timestamp_payment_date_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcredits',
            name='date_paid',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
