# Generated by Django 4.2.3 on 2023-08-05 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('talents', '0002_talent_profile_talent_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('expected_date', models.DateField()),
                ('status', models.CharField(choices=[
                    ('OPEN', 'Open'),
                    ('CLOSED', 'Closed'),
                    ('WIP', 'WIP')
                ], max_length=30)),
                ('award_points', models.PositiveIntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTalent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_points', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talents.talent')),
            ],
        ),
    ]
