# Generated by Django 4.2.3 on 2023-08-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttalent',
            name='award_points',
        ),
        migrations.AddField(
            model_name='projecttalent',
            name='talent_description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
