# Generated by Django 4.2.3 on 2023-08-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_projecttalent_award_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttalent',
            name='award_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
