# Generated by Django 4.2.3 on 2023-08-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0002_talent_profile_talent_resume'),
        ('projects', '0004_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttalent',
            name='talent',
        ),
        migrations.RemoveField(
            model_name='projecttalent',
            name='talent_description',
        ),
        migrations.AddField(
            model_name='projecttalent',
            name='talents',
            field=models.ManyToManyField(to='talents.talent'),
        ),
    ]
