# Generated by Django 4.2.3 on 2023-08-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_reference',
            field=models.CharField(default='INV<django.db.models.fields.related.ForeignKey>2308', max_length=50),
        ),
    ]
