# Generated by Django 4.2.3 on 2023-12-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_invoice_invoice_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_reference',
            field=models.CharField(default='INV<django.db.models.fields.related.ForeignKey>2312', max_length=50),
        ),
    ]
