# Generated by Django 4.2.3 on 2023-07-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_reference', models.CharField(max_length=100, unique=True)),
                ('contract_expiration_date', models.DateField()),
                ('contract_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], max_length=20)),
            ],
        ),
    ]
