# Generated by Django 4.2.3 on 2023-07-26 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.EmailField(max_length=100)),
                ('code', models.EmailField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=300)),
                ('location', models.CharField(default='', max_length=300)),
                ('brand_name', models.CharField(default='', max_length=100)),
                ('country', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clients.country')),
                ('industry', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clients.industry')),
            ],
        ),
    ]
