# Generated by Django 4.2.3 on 2023-07-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Empire DHV', max_length=100)),
                ('invoice_prefix', models.CharField(default='INV', max_length=10)),
                ('quotation_prefix', models.CharField(default='QUO', max_length=10)),
                ('client_prefix', models.CharField(default='CUS', max_length=10)),
                ('product_prefix', models.CharField(default='PRD', max_length=10)),
                ('default_tax', models.FloatField(default=18, max_length=10)),
                ('default_discount', models.FloatField(default=0, max_length=10)),
                ('payment_terms', models.CharField(default='Payment by deposit to company account only', max_length=500)),
                ('contract_prefix', models.CharField(default='CTR', max_length=10)),
                ('date_format', models.CharField(default='%Y-%m-%d', max_length=10)),
                ('company_account', models.CharField(default='0100123012021', max_length=100)),
                ('company_bank_name', models.CharField(default='BANK ACCOUNT NAME', max_length=100)),
                ('company_address', models.TextField(default='Accra, Ghana')),
                ('company_logo', models.FileField(default='', upload_to='static')),
                ('user_identifier', models.CharField(default='estate', max_length=20)),
                ('invoice_theme', models.CharField(choices=[('estate', 'estate'), ('business', 'business'), ('hosting', 'hosting')], default='estate', max_length=20)),
            ],
        ),
    ]
