# Generated by Django 4.2.3 on 2023-07-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='company_logo',
            field=models.FileField(default='static/icon.svg', upload_to='static/'),
        ),
    ]
