# Generated by Django 4.2.3 on 2023-08-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_companysettings_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('description', models.CharField(default='', max_length=400)),
            ],
        ),
    ]
