# Generated by Django 4.2.3 on 2023-08-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='profile',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='talent',
            name='resume',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
