# Generated by Django 4.2.3 on 2023-07-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='quotation_reference',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
