# Generated by Django 4.2.3 on 2023-07-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_reference', models.CharField(max_length=10)),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
